alforis-tablette:
  #---------------------------------------------------#
  #  Palette de couleurs - Cosy & Moderne
  #---------------------------------------------------#
  primary-color: "#E39F70" # Pêche doux
  accent-color: "#9D3A66" # Vieux rose

  # Couleurs de texte
  primary-text-color: "#2E3A48" # Anthracite
  secondary-text-color: "#5A6A7A" # Gris bleuté
  text-primary-color: "#FFFFFF" # Texte sur fond coloré

  # Couleurs de fond
  primary-background-color: "#F8F6F4" # Blanc cassé
  secondary-background-color: "#EFEBE8" # Gris clair chaud

  #---------------------------------------------------#
  #  Cartes (Cards)
  #---------------------------------------------------#
  card-background-color: "rgba(255, 255, 255, 0.85)" # Blanc translucide
  ha-card-background-color: "rgba(255, 255, 255, 0.85)" # Alias pour compatibilité
  ha-card-border-radius: "28px"
  ha-card-box-shadow: "0 12px 32px rgba(46, 58, 72, 0.1)" # Ombre douce et profonde
  ha-card-border-width: "1px"
  ha-card-border-color: "rgba(227, 159, 112, 0.2)" # Bordure pêche très subtile

  #---------------------------------------------------#
  #  Typographie
  #---------------------------------------------------#
  font-family: '"Inter", sans-serif'
  paper-font-common-base_-_font-family: 'var(--font-family)'
  paper-font-common-code_-_font-family: '"Fira Code", monospace'

  #---------------------------------------------------#
  #  Header
  #---------------------------------------------------#
  app-header-background-color: "rgba(248, 246, 244, 0.8)"
  app-header-text-color: "var(--primary-text-color)"
  app-header-border-bottom: "1px solid var(--ha-card-border-color)"

  #---------------------------------------------------#
  #  UI Elements
  #---------------------------------------------------#
  # Boutons, etc.
  paper-item-icon-color: "var(--primary-text-color)"
  paper-item-icon-active-color: "var(--primary-color)"

  # Sliders
  paper-slider-knob-color: "var(--primary-color)"
  paper-slider-knob-start-color: "var(--primary-color)"
  paper-slider-pin-color: "var(--primary-color)"
  paper-slider-active-color: "var(--primary-color)"
  paper-slider-secondary-color: "var(--secondary-background-color)"

  # Labels (badges)
  label-badge-background-color: "var(--secondary-background-color)"
  label-badge-text-color: "var(--secondary-text-color)"
  label-badge-red: "var(--accent-color)"

  # Icônes
  state-icon-color: "var(--primary-text-color)"
  state-icon-active-color: "var(--primary-color)"

  # RGB values for transparent backgrounds
  rgb-primary-color: 227, 159, 112
  rgb-accent-color: 157, 58, 102
  rgb-card-background-color: 255, 255, 255
  rgb-primary-text-color: 46, 58, 72
  rgb-secondary-text-color: 90, 106, 122

  # Custom variables for the modern dashboard
  modern-dashboard-title-font-size: "28px"
  modern-dashboard-title-font-weight: "700"
  modern-dashboard-card-padding: "24px"
  modern-dashboard-grid-gap: "16px"

  # Styles pour les modales (more-info dialogs)
  mdc-dialog-box-shadow: "var(--ha-card-box-shadow)"
  mdc-dialog-bg-color: "var(--primary-background-color)"
  mdc-theme-surface: "var(--primary-background-color)"
  mdc-typography-headline6-font-size: "22px"
  mdc-typography-headline6-font-weight: "600"
  mdc-theme-on-surface: "var(--primary-text-color)"
  mdc-text-field-fill-color: "var(--secondary-background-color)"
  mdc-text-field-ink-color: "var(--primary-text-color)"
  mdc-theme-primary: "var(--primary-color)"
